AWSTemplateFormatVersion: '2010-09-09'
Description: 'Jenkins Stack'

Parameters:
  Project:
    Type: String
  TraineeName:
    Type: String
  InstanceType:
    Type: String
    Description: The instance type
    Default: t2.micro
  ImageId:
    Type: String
    Description: The instance ami id

Resources:
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub "${Project}-public-subnet-a"
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref Project
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 80
          VolumeType: gp2
          DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Sub "${TraineeName}-jenkins-instance"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex

          # Install Jenkins
          yum update -y
          yum remove -y java-1.7.0-openjdk
          yum install -y java-1.8.0
          wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
          rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
          yum install -y jenkins
          service jenkins start